<h2>Iniciar Sesi&oacute;n</h2>

<form action="" name="form1" method="post">
	<input type="hidden" value="1" name="enviar">
	<p>
		<label for="">Usuario</label>
		<input type="text" name="usuario" values="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>">
	</p>
	<p>
		<label for="">Password</label>
		<input type="password" name="pass">
	</p>
	<p>
		<input type="submit" value="Enviar">
	</p>
</form>